module.exports = {
  up: queryInterface =>
    queryInterface.bulkInsert(
      "Schools",
      [
        {
          id: 1,
          name: "Bison bison",
          country: "Capra ibex",
          createdAt: "2020-02-24T06:31:46Z",
          updatedAt: null,
          deletedAt: null,
        },
        {
          id: 2,
          name: "Numida meleagris",
          country: "unavailable",
          createdAt: "2020-01-04T00:43:08Z",
          updatedAt: null,
          deletedAt: null,
        },
        {
          id: 3,
          name: "Zenaida galapagoensis",
          country: "Dasyurus viverrinus",
          createdAt: "2020-05-26T06:40:18Z",
          updatedAt: null,
          deletedAt: null,
        },
        {
          id: 4,
          name: "Pelecans onocratalus",
          country: "unavailable",
          createdAt: "2019-10-14T22:40:52Z",
          updatedAt: null,
          deletedAt: null,
        },
        {
          id: 5,
          name: "Anser anser",
          country: "Cervus canadensis",
          createdAt: "2020-06-15T14:14:02Z",
          updatedAt: null,
          deletedAt: null,
        },
        {
          id: 6,
          name: "Cacatua tenuirostris",
          country: "Conolophus subcristatus",
          createdAt: "2019-09-14T09:15:30Z",
          updatedAt: null,
          deletedAt: null,
        },
        {
          id: 7,
          name: "Odocoileus hemionus",
          country: "Leptoptilos crumeniferus",
          createdAt: "2019-11-13T08:48:19Z",
          updatedAt: null,
          deletedAt: null,
        },
        {
          id: 8,
          name: "Ninox superciliaris",
          country: "Aonyx capensis",
          createdAt: "2020-06-23T23:01:47Z",
          updatedAt: null,
          deletedAt: null,
        },
        {
          id: 9,
          name: "Panthera pardus",
          country: "Sciurus niger",
          createdAt: "2020-06-13T15:57:03Z",
          updatedAt: null,
          deletedAt: null,
        },
        {
          id: 10,
          name: "Francolinus leucoscepus",
          country: "Recurvirostra avosetta",
          createdAt: "2019-09-20T08:47:02Z",
          updatedAt: null,
          deletedAt: null,
        },
        {
          id: 11,
          name: "Oreamnos americanus",
          country: "Streptopelia decipiens",
          createdAt: "2019-12-12T22:28:31Z",
          updatedAt: null,
          deletedAt: null,
        },
        {
          id: 12,
          name: "Phalaropus lobatus",
          country: "Speothos vanaticus",
          createdAt: "2020-02-19T23:47:09Z",
          updatedAt: null,
          deletedAt: null,
        },
        {
          id: 13,
          name: "Dasyurus viverrinus",
          country: "Phalacrocorax carbo",
          createdAt: "2019-11-12T21:41:30Z",
          updatedAt: null,
          deletedAt: null,
        },
        {
          id: 14,
          name: "Haliaetus leucogaster",
          country: "Dendrocitta vagabunda",
          createdAt: "2020-04-21T00:29:00Z",
          updatedAt: null,
          deletedAt: null,
        },
        {
          id: 15,
          name: "Pelecanus conspicillatus",
          country: "Odocoilenaus virginianus",
          createdAt: "2019-08-26T20:51:37Z",
          updatedAt: null,
          deletedAt: null,
        },
      ],
      {}
    ),

  down: queryInterface => queryInterface.bulkDelete("Schools", null, {}),
};
