module.exports = {
	up: queryInterface =>
		queryInterface.bulkInsert(
			'Schools',
			[
				{
					id: 1,
					name: 'Calaba',
					countryId: 1,
					code: 3,
					programId: 1,
					clusterId: 1,
				},
				{
					id: 2,
					name: 'Grafton',
					countryId: 1,
					code: 4,
					programId: 1,
					clusterId: 1,
				},
				{
					id: 3,
					name: 'Waterloo',
					countryId: 1,
					code: 5,
					programId: 1,
					clusterId: 1,
				},
				{
					id: 4,
					name: 'Babadorie',
					countryId: 1,
					code: 7,
					programId: 1,
					clusterId: 1,
				},
				{
					id: 5,
					name: 'Goderich',
					countryId: 1,
					code: 9,
					programId: 1,
					clusterId: 1,
				},
				{
					id: 6,
					name: 'Cecelia A. Dunbar',
					countryId: 2,
					code: 1,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 7,
					name: 'Malema Public School',
					countryId: 2,
					code: 2,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 8,
					name: 'Sumo Town Public School',
					countryId: 2,
					code: 3,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 9,
					name: 'Weajor Public School',
					countryId: 2,
					code: 4,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 10,
					name: 'Zunna Town Public school',
					countryId: 2,
					code: 5,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 11,
					name: 'J.L Travers Public School',
					countryId: 2,
					code: 6,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 12,
					name: 'Newcess Public School',
					countryId: 2,
					code: 7,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 13,
					name: 'Boe Dayugar',
					countryId: 2,
					code: 8,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 14,
					name: 'Sayouh Public School',
					countryId: 2,
					code: 9,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 15,
					name: 'Siahn Public School',
					countryId: 2,
					code: 10,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 16,
					name: 'Elementary Demonstration',
					countryId: 2,
					code: 11,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 17,
					name: 'Cecilia Nepe Elementary',
					countryId: 2,
					code: 12,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 18,
					name: 'Louisiana Elementary',
					countryId: 2,
					code: 13,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 19,
					name: 'Sinoe Community',
					countryId: 2,
					code: 14,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 20,
					name: 'Lower Juarzon',
					countryId: 2,
					code: 15,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 21,
					name: 'Frank Brown Elem/Jr High School',
					countryId: 2,
					code: 16,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 22,
					name: 'Upper Wedjah Public',
					countryId: 2,
					code: 17,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 23,
					name: 'Chewlue Town',
					countryId: 2,
					code: 18,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 24,
					name: 'James Edward Greene',
					countryId: 2,
					code: 19,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 25,
					name: 'Nyarn',
					countryId: 2,
					code: 20,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 26,
					name: 'J N George',
					countryId: 2,
					code: 21,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 27,
					name: 'Nyaake Community School',
					countryId: 2,
					code: 22,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 28,
					name: 'Konowroken Demonstration School',
					countryId: 2,
					code: 23,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 29,
					name: 'Suwroken Community Schoo',
					countryId: 2,
					code: 24,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 30,
					name: 'Wlegboken Public School',
					countryId: 2,
					code: 25,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 31,
					name: 'Gbalaken Public School',
					countryId: 2,
					code: 26,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 32,
					name: 'Karloken Demonstration',
					countryId: 2,
					code: 27,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 33,
					name: 'Suasu Public School',
					countryId: 2,
					code: 28,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 34,
					name: 'Susanna P. Brewer',
					countryId: 2,
					code: 29,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 35,
					name: 'Nyentiabo Public School',
					countryId: 2,
					code: 30,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 36,
					name: 'Nyantujah Elem./Jr. High School',
					countryId: 2,
					code: 31,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 37,
					name: 'Frances Nyenfueh Public School',
					countryId: 2,
					code: 32,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 38,
					name: 'Chlorobo Elem/Jr High School',
					countryId: 2,
					code: 33,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 39,
					name: 'E. Segbeh Brooks Public School',
					countryId: 2,
					code: 34,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 40,
					name: 'A. B. Kromah School School',
					countryId: 2,
					code: 35,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 41,
					name: 'Dendewea/Layne Public School',
					countryId: 2,
					code: 36,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 42,
					name: 'Jebbeh Kiazolu Public School',
					countryId: 2,
					code: 37,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 43,
					name: 'Jundu Public School',
					countryId: 2,
					code: 38,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 44,
					name: 'Konjah Public School',
					countryId: 2,
					code: 39,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 45,
					name: 'Kparlen Public School',
					countryId: 2,
					code: 40,
					programId: 2,
					clusterId: 2,
				},

				{
					id: 46,
					name: 'Latia Public School',
					countryId: 2,
					code: 41,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 47,
					name: 'Madina Elem/Jr High School',
					countryId: 2,
					code: 42,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 48,
					name: 'Mani Public School',
					countryId: 2,
					code: 43,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 49,
					name: 'Robertsport High School',
					countryId: 2,
					code: 44,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 50,
					name: 'Sembehun Public School',
					countryId: 2,
					code: 45,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 51,
					name: 'Sinje Public School',
					countryId: 2,
					code: 46,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 52,
					name: 'Kingsville Kindergarten',
					countryId: 2,
					code: 47,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 53,
					name: 'Euphemia Barclay',
					countryId: 2,
					code: 48,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 54,
					name: 'E. J. Yancy Public School',
					countryId: 2,
					code: 49,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 55,
					name: 'Paye Public Public School',
					countryId: 2,
					code: 50,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 56,
					name: 'Massaquoi Ta Public',
					countryId: 2,
					code: 51,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 57,
					name: 'Poye Public School',
					countryId: 2,
					code: 52,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 58,
					name: 'Government Central',
					countryId: 2,
					code: 53,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 59,
					name: 'Kpalawen Public School',
					countryId: 2,
					code: 54,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 60,
					name: 'Gleegbar-ta Public School',
					countryId: 2,
					code: 55,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 61,
					name: 'Government Day Elem/JR High',
					countryId: 2,
					code: 56,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 62,
					name: 'Toe Town Public',
					countryId: 2,
					code: 57,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 63,
					name: 'Yahlon Public School',
					countryId: 2,
					code: 58,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 64,
					name: 'Gleozohn Public School',
					countryId: 2,
					code: 59,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 65,
					name: 'Little Kola Public School',
					countryId: 2,
					code: 60,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 66,
					name: 'Grand Kola Public',
					countryId: 2,
					code: 61,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 68,
					name: 'Martha S. Dunn',
					countryId: 2,
					code: 62,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 69,
					name: 'Trude Public Schoo',
					countryId: 2,
					code: 63,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 70,
					name: 'Government Morning Elem sch, Hartford',
					countryId: 2,
					code: 64,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 71,
					name: 'Rev. Gardner Memorial',
					countryId: 2,
					code: 65,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 72,
					name: 'Mende Town Public School (ex Omega Sch)',
					countryId: 2,
					code: 66,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 73,
					name: 'Robertsville Public School',
					countryId: 2,
					code: 67,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 74,
					name: 'Islamic Model School',
					countryId: 2,
					code: 68,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 75,
					name: 'Karloken Public School (Jr/SHS)',
					countryId: 2,
					code: 69,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 76,
					name: 'Kollie Town Elem School',
					countryId: 2,
					code: 70,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 77,
					name: 'Sekally Elem School',
					countryId: 2,
					code: 71,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 78,
					name: 'Tubmanville',
					countryId: 2,
					code: 72,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 79,
					name: 'Mambah Central Academy #3',
					countryId: 2,
					code: 73,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 80,
					name: 'Mambah Central Academy #1',
					countryId: 2,
					code: 74,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 81,
					name: 'Paynesberry Public School',
					countryId: 2,
					code: 75,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 82,
					name: 'Augustine F. Caine',
					countryId: 2,
					code: 76,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 83,
					name: 'Jeremiah B. Gardee Public School',
					countryId: 2,
					code: 77,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 84,
					name: 'Upper Buchanan School',
					countryId: 2,
					code: 78,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 85,
					name: 'Gio Town Public School (Grade3-6 only)',
					countryId: 2,
					code: 79,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 86,
					name: 'Isaac G. Tondo Public School',
					countryId: 2,
					code: 80,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 87,
					name: 'Cecelia W. Bryant',
					countryId: 2,
					code: 81,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 88,
					name: 'Gianda Elem/JR High',
					countryId: 2,
					code: 82,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 89,
					name: 'Kamara Town Public',
					countryId: 2,
					code: 83,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 90,
					name: 'Ben Town Public School',
					countryId: 2,
					code: 84,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 91,
					name: 'Korkor David Public School',
					countryId: 2,
					code: 85,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 92,
					name: 'Jesus christ Children Community',
					countryId: 2,
					code: 86,
					programId: 2,
					clusterId: 2,
				},
				{
					id: 93,
					name: 'Annie Banks Public School (morning session)',
					countryId: 2,
					code: 87,
					programId: 2,
					clusterId: 2,
				},
			],
			{},
		),

	down: queryInterface =>
		queryInterface.bulkDelete('Schools', null, {}),
};
